app1/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # /app1
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^plot1d/$', views.Plot1DView.as_view(), name='plot1d'),
    url(r'^plot1d_multiple/(?P<n>\d+)/$',
        views.Plot1DMultipleView.as_view(), name='plot1d_multiple'),
    

]

site1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/app1/'), name='index'),
    url(r'^app1/',  include(('app1.urls', 'app1'), namespace='app1', )),
]

app1/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app1/views.py
import logging

from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.views.generic import TemplateView

from . import plots

logger = logging.getLogger(__name__)


class IndexView(TemplateView):
    template_name = "index.html"


class Plot1DView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot1DView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot1d()
        return context



class Plot1DMultipleView(TemplateView):
    template_name = "plot_multiple.html"

    def get_context_data(self, **kwargs):
        n = int(kwargs['n'])
        # Call the base implementation first to get a context
        context = super(Plot1DMultipleView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot1d_multiple(n)
        return context


def plot1d_multiple_ajax(request, n):
    """
    Only handles AJAX queries
    """
    logger.debug("Plotting {} plots.".format(n))
    return HttpResponse(plots.plot1d_multiple(int(n)))

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <title>PlotLy OffLine examples</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  
  {% endblock %}
</head>
<body>
  {% block content %}
  <!-- Content goes here -->

  {% endblock %}

  {% block tail %}
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  {% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h1>Integrating PlotLy into DJango</h1>
  <p class="lead">Click on the buttons below to see the examples.</p>
</div>

<div class="container">
  <table class="table table-striped table-hover">
    <tr>
      <td>1D</td>
      <td><a class="btn btn-default" href="{% url 'app1:plot1d' %}" role="button">View</a></td>
    </tr>
    
    <tr>
      <td>Random 1D (Ajax)</td>
      <td><a class="btn btn-default" href="{% url 'app1:plot1d_multiple' 1 %}" role="button">View</a></td>
    </tr>
    
  </table>
</div>
<!-- /.container -->

{% endblock %}

templates/plot.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Plot using Plot.ly</h1>
  <p class="lead">Here we go...</p>
</div>
<!-- /.container -->

<div class="container">
  <div class="row" style="border: 1px solid black">
    {# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
    <div class="col-md-12">{{plot|safe}}</div>
  </div>
</div>
<!-- /.container -->


<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>

{% endblock %}

templates/plot_multiple.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Plot using Plot.ly</h1>
  <p class="lead">Ajax test!</p>
</div>
<!-- /.container -->

<div class="container">
  <div class="row">
    <div class="col-md-12"><div id="plot">{{plot|safe}}</div></div>
  </div>
</div>
<!-- /.container -->



<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
{% endblock %}